### ISSUE TITLE
"Audio Devices" button causes game crash

### ISSUE THREAD

**Issue by QuantumStatement** [ironrainomega/Audiomanager#1]
Minecraft 1.12.2
Forge 14.23.5.2796
Audiomanager 0.0.1

Game crashes when I press "Audio Devices" button in Options menu
Crash report:
[crash-2019-01-06_19.01.16-client.txt](https://github.com/ironrainomega/Audiomanager/files/2730614/crash-2019-01-06_19.01.16-client.txt)

**Comment by ironrainomega** [comment]
Please try with 0.0.2 - I pushed a fix to CurseForge (https://minecraft.curseforge.com/projects/audiomanager/files/2657065 - once approved). If you're still crashing, please provide the crash log but also details about your audio setup and OS.

Thank you for reporting!

**Comment by QuantumStatement** [comment]
Update fixes the crash
But why mod can't find audio devices? I have at least 3 active devices
![sounddevices](https://user-images.githubusercontent.com/35406698/50740149-6c1fd600-11fb-11e9-9ddf-ccf7aa2298ce.png)

Maybe mod don't like Bluetooth headphones...

**Comment by QuantumStatement** [comment]
Just tested it - mod changes devices if I connect/disconnect BT headphones

**Comment by ironrainomega** [comment]
It's not the mod but OpenAL that doesn't seem to be able to grab the Audio Devices. It's weird, I'll try to test this out further. 

Thank you for this!!! You're awesome :-)
